import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'vite';
import { renderToStaticMarkup } from 'react-dom/server';
import { createElement } from 'react';
import { discoverIssues } from '../dist/server/discovery.js';
import { fixture, boardFiles } from './fixtures.mjs';

test('renders each workflow with its own columns, real context, and readable attention entries', async (t) => {
  const root = await fixture(t, boardFiles);
  const data = await discoverIssues(root);
  const vite = await createServer({ server: { middlewareMode: true, hmr: false, ws: false }, appType: 'custom' });
  t.after(() => vite.close());
  const { BoardView } = await vite.ssrLoadModule('/Board.tsx');
  const implementation = renderToStaticMarkup(createElement(BoardView, { data, workflow: 'implementation' }));
  assert.match(implementation, /ready-for-agent/);
  assert.match(implementation, /needs-triage/);
  assert.match(implementation, /#02/);
  assert.match(implementation, /Start/);
  assert.match(implementation, /alpha/);
  assert.match(implementation, /\.scratch\/alpha\/issues/);
  assert.doesNotMatch(implementation, />Question</);
  assert.match(implementation, /Needs attention/);
  assert.match(implementation, /Unknown status: done/);
  assert.match(implementation, /<pre[^>]*># 03: Broken/);
  const sameColumn = { ...data, issues: data.issues.map((issue) => issue.title === 'Later' ? { ...issue, status: 'ready-for-agent' } : issue) };
  const sorted = renderToStaticMarkup(createElement(BoardView, { data: sameColumn, workflow: 'implementation' }));
  assert.ok(sorted.indexOf('Start') < sorted.indexOf('Later'));
  const wayfinding = renderToStaticMarkup(createElement(BoardView, { data, workflow: 'wayfinding' }));
  assert.match(wayfinding, /Question/);
  assert.match(wayfinding, /Review/);
  assert.match(wayfinding, /claimed/);
  assert.match(wayfinding, /resolved/);
  assert.doesNotMatch(wayfinding, /ready-for-agent|>Start</);
  const hostile = { ...data, issues: [{ ...data.issues[0], title: '<script>alert(1)</script>', workflow: null, diagnostics: ['<img src=x onerror=alert(1)>'], content: '<script>alert(1)</script>' }] };
  const attention = renderToStaticMarkup(createElement(BoardView, { data: hostile, workflow: 'implementation' }));
  assert.doesNotMatch(attention, /<script>|<img /);
  assert.match(attention, /&lt;script&gt;/);
});
